import 'dart:math';

/// Barcode auto-generation for grid-mode business types (cafe/restaurant/playstation).
///
/// Generated barcodes use the `auto-` prefix followed by microseconds since
/// epoch + a random suffix, guaranteeing uniqueness across saves and never
/// colliding with scanner-mode numeric imports.
String generateAutoBarcode() {
  final micros = DateTime.now().microsecondsSinceEpoch;
  final random = Random().nextInt(10000).toString().padLeft(4, '0');
  return 'auto-$micros$random';
}

/// Returns true when [barcode] was generated by [generateAutoBarcode].
bool isAutoBarcode(String barcode) => barcode.startsWith('auto-');

/// Generates a scannable 12-digit numeric barcode (first digit 1-9),
/// regenerating while [isTaken] reports a collision.
String generateNumericBarcode({bool Function(String)? isTaken}) {
  final taken = isTaken ?? (_) => false;
  for (var attempt = 0; attempt < 100; attempt++) {
    final candidate =
        '${Random().nextInt(9) + 1}${List.generate(11, (_) => Random().nextInt(10)).join()}';
    if (!taken(candidate)) return candidate;
  }
  return '${Random().nextInt(9) + 1}${List.generate(11, (_) => Random().nextInt(10)).join()}';
}
