/// Barcode auto-generation for grid-mode business types (cafe/restaurant/playstation).
///
/// Generated barcodes use the `auto-` prefix followed by microseconds since
/// epoch, guaranteeing uniqueness across saves and never colliding with
/// scanner-mode numeric imports.
String generateAutoBarcode() => 'auto-${DateTime.now().microsecondsSinceEpoch}';

/// Returns true when [barcode] was generated by [generateAutoBarcode].
bool isAutoBarcode(String barcode) => barcode.startsWith('auto-');
