import 'dart:math';

/// Barcode auto-generation for grid-mode business types (cafe/restaurant/playstation).
///
/// Generated barcodes use the `auto-` prefix followed by microseconds since
/// epoch + a random suffix, guaranteeing uniqueness across saves and never
/// colliding with scanner-mode numeric imports.
String generateAutoBarcode() {
  final micros = DateTime.now().microsecondsSinceEpoch;
  final random = Random().nextInt(10000).toString().padLeft(4, '0');
  return 'auto-$micros$random';
}

/// Returns true when [barcode] was generated by [generateAutoBarcode].
bool isAutoBarcode(String barcode) => barcode.startsWith('auto-');
