name: Linux Minimal Test

on:
  push:
    branches:
      - development

jobs:
  test:
    name: Linux Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Test PrintServer.Linux Build
        run: |
          cd PrintServer.Linux
          dotnet build PrintServer.Linux.csproj -c Release -r linux-x64