name: Test Linux CI

on:
  push:
    branches:
      - feature/*

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Test workflow works!"
