const Map<String, String> defaultBindings = {
  'nav.checkout': 'f1',
  'nav.inventory': 'f2',
  'nav.sales': 'f3',
  'nav.settings': 'f4',
  'search.toggle': 'f5',
  'search.toggle.slash': '/',
  'search.toggle.ctrl': 'ctrl+f',
  'cart.confirm': 'f12',
  'cart.confirm.space': 'space',
  'cart.selected.up': 'arrowUp',
  'cart.selected.down': 'arrowDown',
  'cart.selected.delete': 'delete',
  'cart.quick.1': 'alt+1',
  'cart.quick.2': 'alt+2',
  'cart.quick.3': 'alt+3',
  'cart.quick.4': 'alt+4',
  'cart.quick.5': 'alt+5',
  'cart.quick.6': 'alt+6',
  'cart.quick.7': 'alt+7',
  'cart.quick.8': 'alt+8',
};
